RegisterProviders method
jmcdo29/nest-commander pull request #706
Opened 2022-12-24 21:03 UTC by tkow

Close https://github.com/jmcdo29/nest-commander/issues/705

2022-12-24 21:16 UTC, tkow commented
@jmcdo29
Please, close it if you don't like it as describing in https://github.com/jmcdo29/nest-commander/issues/705.

2022-12-24 22:38 UTC, jmcdo29 commented on packages/nest-commander/src/command-runner.interface.ts
> +  static registerCommands(meta: string = CommandMeta): CommandRunnerClass[] {
Could we call this `registerWithSubCommands`? That way the intent is clear. The code is actually really clean, and if the command is clear enough then I don't see why we can't add it in. Thanks for adding the tests too, showing it works is really nice.

The only other thing I would ask is can you update the documentation? Just a new section in the [`Commander`](https://nest-commander.jaymcdoniel.dev/en/features/commander/) section would do

2022-12-25 01:03 UTC, jmcdo29 commented
Oh, also, would you mind running `pnpm changeset` and following the wizard to create a `minor` changeset for the `nest-commander` package? That will help automate the release of this once I merge it in.

2022-12-25 06:02 UTC, jmcdo29 requested changes
A couple of grammatical revisions. Thanks for all the work!

2022-12-25 06:02 UTC, jmcdo29 commented on apps/docs/src/pages/en/features/commander.md
> +Though you'll find the details are in [factory page](./factory), you must register your all commands including sub commands as providers in your module class exists somewhere in Module tree registerd
```suggestion
Though you'll find the implementation details in the [factory page](./factory), you must register all of your commands including the sub commands as providers in a module class that the `CommandFactory` ends up registering. For convenience, given that we register examples in Sub Commands section and set them as providers in `app.module.ts` that set as root module to `CommandFactory`.
```

2022-12-25 06:05 UTC, jmcdo29 commented
If everything (save for the sending coverage) passes, this PR will be great! Thanks again.

2022-12-25 06:19 UTC, tkow commented
@jmcdo29 

Thank you for reviews, in fact, I'm not native English speaker, so I apologize for many grammatical mistakes.

I have no idea to fix CI / send-coverage, so could  I ask you to fix it?

BTW, I really think this library is awesome and I have been making many our command line tools standalone and want more known widely especially in my country, Japan. It can be used not for nest application but for command line tools builder.  If you don't mind it,  could you let me translate docs in ja locale?
And, sorry for that I make you work even thought today is Xmas. I'll give you  my gratitude sponsored page though it may be little for you. Have a nice day.

2022-12-25 06:35 UTC, jmcdo29 commented
> I have no idea to fix CI / send-coverage, so could I ask you how to fix it?

It's just because of a missing API token for Codacy. Don't worry about it :)

2022-12-25 06:38 UTC, jmcdo29 commented
> If you don't mind it, could you let me translate docs in ja locale when I have time?

Go for it! So long as you don't mind helping maintain them as well when changes happen :smile: I use [AstroDocs](https://github.com/withastro/astro/tree/latest/examples/docs?on=github#multiple-languages-support) for the documentation, which has multiple language support already built in.

2022-12-25 06:44 UTC, tkow commented
@jmcdo29 

> It's just because of a missing API token for Codacy. Don't worry about it :)

So, Is there nothing I should change in this PR? 
> If everything (save for the sending coverage) passes, this PR will be great! Thanks again.
Sorry for I'm not familiar to nx e2e test, but I still have something to have to add extra configuration to do this.

2022-12-25 06:47 UTC, jmcdo29 commented
> So, Is there nothing I should change in this PR?

Nah, it's all good

2022-12-25 08:07 UTC, jmcdo29 approved these changes

2022-12-30 18:17 UTC, merged